plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
}

if (rootProject.ext.useOBuildEnabled) {
    apply from: "${rootDir}/opipeline.gradle"
}

android {
    namespace 'com.oplus.pantanal.namespace'
    compileSdk 33

    defaultConfig {
        applicationId "com.oplus.pantanal.namespace"
        minSdk 30
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    // 品牌，公司流水线上传产物时要求有这个维度，否则流水线生产会失败
    flavorDimensions "brand"

    productFlavors {
        oppo {
            dimension "brand"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    buildFeatures {
        viewBinding true
    }
}

android.applicationVariants.all { variant ->
    variant.outputs.all { variantOutput ->
        String fileName = outputFileName
        // 公司流水线对命名有要求
        fileName = fileName
                .replace("-OPPO", "-OPPO-all")
        outputFileName = fileName
    }
}

dependencies {
    implementation project(':mylibrary3')
    implementation 'androidx.core:core-ktx:1.9.0'
    implementation 'androidx.appcompat:appcompat:1.5.1'
    implementation 'com.google.android.material:material:1.7.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation 'androidx.navigation:navigation-fragment-ktx:2.5.3'
    implementation 'androidx.navigation:navigation-ui-ktx:2.5.3'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.4'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.0'
}